defaultPortal: DT
portals:
  - name: DT
    portalId: 9242831
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CIKogen4LhIIAA0ABAAA4AEYz5G0BCCuppUFKO7pDDIZANxAY3ERV2p5k0Jksif7PzmMnUJaELj_PTogAAAEQQAAAHgAAAAAAAAAAIAAAAAAAAAEAADAB2D-_zFCGQDcQGNxvCIOJt511MEwNNQ9jIhOQP9mNQQ
        expiresAt: '2021-02-10T18:07:22.124Z'
    personalAccessKey: >-
      CiQzOWRiMzg2Mi1lOGQ5LTQxNTUtYjEyNC1kNDQ5MDc4MGNmMjMQz5G0BBiuppUFKhkABeaRgr80e1YfvTj0crnAJtXZjBnv9CIe
